deployments:
  - name: frontend
    image: danilkolmahin/master-diploma
  - name: backend
    image: danilkolmahin/master-diploma
    env:
      DATABASE_PASSWORD:

services:
  - app: frontend
  - app: backend

ingresses:
  - service: frontend
    host: localhost
    path: /
  - service: backend
    host: localhost
    path: /{whatever:.+}

secrets:
  DATABASE_PASSWORD:
