deployments:
  - name: frontend
    image: danilkolmahin/master-diploma
  - name: backend
    image: danilkolmahin/master-diploma
    env:
      DATABASE_PASSWORD:
      JWT_SECRET:

services:
  - app: frontend
  - app: backend

ingresses:
  - service: backend
    host: localhost
    paths:
      - /api{whatever:.*}
  - service: frontend
    host: localhost
    paths:
      - /{whatever:.+}

secrets:
  DATABASE_PASSWORD:
  JWT_SECRET:
