{{ range .Values.ingresses }}
{{- $service := .service -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $service }}
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: {{ .clusterIssuer }}
spec:
  tls:
  - hosts:
    - {{ .host }}
    secretName: {{ $service }}
  rules:
  - host: {{ .host }}
    http:
      paths:
      {{ range .paths }}
      - backend:
          service:
            name: {{ $service }}
            port:
              number: 80
        path: {{ . }}
        pathType: Exact
      {{ end }}
---
{{ end }}
