@startuml authorization
actor Клієнт as Client
participant Система as System

Client -> System : Запит на авторизацію
note right
  Клієнт ініціює процес challenge-response
end note
System -> System : Генерація випадкового повідомлення
System -> System : Шифрування повідомлення
note left
  Для шифрування використовується публічний
  ключ користувача переданий при реєстрації
end note
System -> System : Збереження випробування
note left
  Випробування зберігається разом з
  вказівником на користувача та TTL випробування
end note
System -> Client : Відправка випробування користувачу

Client -> Client : Розшифровка випробування приватним ключем
Client -> System : Відправка розв'язаного випробування

System -> System : Перевірка випробування
note left
  Умовами проходження випробування є відповідність
  повідомлення початковому і вчасність розв'язання випробування
end note
alt Випробування пройдено
  System -> Client : Повернення успішного статусу авторизації
  note right
    Користувачу на певний час видається http-only cookie
  end note
else Випробування провалено
  System -> Client : Повернення помилки при авторизації
end
@enduml
