@startuml registration
actor Клієнт as Client
participant Система as System

Client -> Client : Генерація криптографічної пари ключів
Client -> Client : Збереження приватного ключа
Client -> System : Запит на реєстрацію
note right
  В запиті на реєстрацію користувач передає email та
  публічний ключ, яким в подальшому оперуватиме система
end note
System -> System : Реєстрація користувача у системі
System -> System : Створення проекту
System -> System : Додавання користувача до проекту
System -> System : Призначення користувачу ролі root (наявні всі права)
System -> Client : Повідомлення про успішну реєстрацію
@enduml
