@startuml registration-via-invite
actor "Зареєстрований користувач" as Inviter
actor "Запрошуваний користувач" as Invitee
participant "Система" as System

== Запрошення користувача ==

Inviter -> System : Запит на доєднання користувача до проекту
note right
  В запиті користувач вказує емейл з яким новий
  користувач має доєднатись
end note
System -> System : Генерація токену
note left
  Токен зберігається для подальшої верифікації під час
  реєстрації. Токен зберігається з TTL
end note
System -> Inviter : Токен запрошення
note right
  Зареєстрований користувач має передати
  токен запрошуваному безпечним шляхом.
end note

== Реєстрація запрошуваного користувача ==

Invitee -> System : Запит на реєстрацію
note left
  Запрошуваний проходить стандартну процедуру
  реєстрації, окрім того, що для доєднання до
  проекту має надати відповідний токен
end note
alt Реєстраційні дані відповідають запрошення
  System -> System : Реєстрація користувача у системі
  System -> System : Додавання користувача до проекту
  System -> System : Призначення користувачу ролі none (відсутні всі права)
  System -> Invitee : Повідомлення про успішну реєстрцію
else Реєстраційні дані не відповідають запрошення
  System -> Invitee : Повідомлення про помилку
end
@enduml
