@startuml schematic-diagram

autonumber

title PGP-RBAC granular access safeguarding model \n Гранулярна модель захисту доступів на основі PGP-RBAC

actor "Користувач" as User
participant "Система" as System

== Safeguarding new entity with data\n(Захист нової сутності з її даними) ==
User -> User : Генерація симетричного ключа
note right
  На цьому етапі користувач вже визначився з тим,
  в рамках якої сутності він бажає зберегти певні дані
end note
User -> User : Шифрування даних симетричним ключем
User -> User : Шифрування симетричного ключа власним публічним ключем
User -> System : Збереження, так званого, SecurityKey
note right
  SecurityKey це сутність що в собі зберігає шифрований
  симетричний ключ, а також посилання на сутність яка пов'язана
  з цим ключем і користувача що має відповідний доступ
end note
User -> System : Збереження даних зашифрованих у **2**

== Reading secured data\n(Читання зашифрованих даних) ==
User -> System : Запит на отримання зашифрованих даних
System -> User : Повернення зашифрованих даних разом з відповідним SecurityKey
User -> User : Розшифровка SecurityKey приватним ключем
User -> User : Розшифровка зашифрованих даних симетричним ключем (розшифрованим SecurityKey)

== Spreading access to other users\n(Роздача доступів іншим користувачам) ==
User -> System : Запит на перелік необхідних SecurityKeys для зміни ролі іншого користувача
note right
  Зміна (роздача) прав можлива лише зі зміною ролі, роль
  визначається переліком прав згідно RBAC
end note
alt Користувач що запитує має доступ до SecurityKeys що вимагає роль
  System -> User : Повернення необхідних SecurityKeys
  User -> System : Запит публічного ключа користувача якому буде змінена роль
  System -> User : Повернення публічного ключа
  User -> User : Розшифровка SecurityKeys власним приватним ключем
  User -> User : Шифрування SecurityKeys чужим публічним ключем
  User -> System : Запит на зміну ролі, що включає перезашифровані SecurityKeys
  alt Запит задовільняє умови зміни ролі
    System -> System : Зміна ролі, збереження SecurityKeys
  else Запит не задовільняє умови зміни ролі
    System -> User : Повернення помилки нестачі прав
  end
else Користувач що запитує не має доступ до SecurityKeys що вимагає роль
  System -> User : Повернення помилки нестачі прав
end

@enduml
