name: CI-CD

on:
  # push:
  #   branches:
  #   - main
  # pull_request:
  #   branches:
  #   - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'
      - run: npm i
      - run: echo "VERSION=$(npm pkg get version | tr -d \")" >> $GITHUB_ENV
      - run: VERSION=${{ env.VERSION }} npm run build-projects
      - uses: docker/login-action@v3
        with:
          username: danilkolmahin
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker push danilkolmahin/master-diploma -a
      - run: |
          curl -Lo ./res.tar.gz https://get.helm.sh/helm-v3.13.3-linux-amd64.tar.gz
          tar -zxvf res.tar.gz
          mv linux-amd64/helm /usr/local/bin
          rm -fr res.tar.gz linux-amd64/
      - run: |
          echo "version: ${{ env.VERSION }}" >> Chart.yaml
      - run: |
          mkdir $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config
          chmod 644 $HOME/.kube/config
          helm upgrade -i -f values.yaml master-diploma . \
          --set version=${{ env.VERSION }} \
          --set secrets.DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
          --set secrets.JWT_SECRET=${{ secrets.JWT_SECRET }} --debug
